### ISSUE TITLE
langchain-postgres on conda-forge

### ISSUE THREAD

**Issue by Sachin-Bhat** [langchain-ai/langchain-postgres#58]
I was trying to check if langchain-postgres was available on conda-forge but could not find it. Requesting a possible offering on conda-forge.

Cheers,
Sachin

**Comment by Sachin-Bhat** [comment]
I ran the following via `grayskull`:

```
grayskull pypi --strict-conda-forge langchain-postgres
```

and got the following meta.yml file:
```
{% set name = "langchain-postgres" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_postgres-{{ version }}.tar.gz
  sha256: ddac1efd183da39f2171b6953a3f74ed70e429e064d33559fd970fe5ad10b477

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - langchain-core >=0.1.50,<0.3
    - psycopg >=3.0.0,<4.0.0
    - psycopg-pool >=3.2.1,<4.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - pgvector >=0.2.5,<0.3.0
    - numpy >=1.0.0,<2.0.0

test:
  imports:
    - langchain_postgres
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-postgres
  summary: An integration package connecting Postgres and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sachin-Bhat

```
